<?php
// This file is generated by .github/workflows/deploy.yml from this template.
// Do not edit the deployed copy on the server directly — edit this template
// and push, or changes will be overwritten on the next deploy.

if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgSitename = "__WG_SITE_NAME__";
$wgMetaNamespace = "FIGHTORDER";

$wgServer = "__WG_SERVER__";

// MediaWiki is installed at the docroot root, so scripts (index.php,
// load.php) live at "/". Must be set explicitly: $wgScriptPath otherwise
// defaults to "/wiki", which makes MediaWiki emit resource URLs like
// /wiki/load.php — those then get caught by the /wiki/ rewrite in
// .htaccess and routed to index.php, so every stylesheet returns HTML
// instead of CSS and the wiki renders completely unstyled.
$wgScriptPath = "";

$wgResourceBasePath = $wgScriptPath;
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

$wgEnableEmail = true;
$wgEnableUserEmail = true;
$wgEmergencyContact = "__WG_EMERGENCY_CONTACT__";
$wgPasswordSender = "__WG_EMERGENCY_CONTACT__";

$wgEnotifUserTalk = false;
$wgEnotifWatchlist = false;
$wgEmailAuthentication = true;

$wgDBtype = "mysql";
$wgDBserver = "__WG_DB_HOST__";
$wgDBname = "__WG_DB_NAME__";
$wgDBuser = "__WG_DB_USER__";
$wgDBpassword = "__WG_DB_PASSWORD__";

$wgDBprefix = "";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

$wgSharedTables[] = "actor";

$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

$wgMainWANCache = CACHE_NONE;

$wgUpgradeKey = "__WG_UPGRADE_KEY__";

$wgLanguageCode = "en";
$wgLocaltimezone = "UTC";

$wgSecretKey = "__WG_SECRET_KEY__";

$wgAuthenticationTokenVersion = "1";

$wgDefaultSkin = "vector-2022";

wfLoadSkin( 'Vector' );

$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['createpage'] = false;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['createpage'] = true;

$wgJobRunRate = 0;
